swagger: '2.0'
info:
  title: CTI Dashboard API
  description: API for managing Cyber Threat Intelligence data.
  version: 1.0.0
host: YOUR_API_GATEWAY_HOST_WILL_GO_HERE
schemes:
  - https
produces:
  - application/json

x-google-backend:
  address: https://europe-west2-cti-dashboard-459422.cloudfunctions.net/api
  path_translation: APPEND_PATH_TO_ADDRESS
  protocol: h2

paths:
  /health:
    get:
      summary: Health Check for the API Gateway and Backend
      operationId: healthCheckGateway
      responses:
        '200':
          description: OK

  /server-time:
    get:
      summary: Get current server time from the backend
      operationId: getServerTimeGateway
      responses:
        '200':
          description: OK

  /firestore-test:
    get:
      summary: Test Firestore Connection
      operationId: testFirestoreGateway
      responses:
        '200':
          description: Test document fetched successfully.
        '201':
          description: Test document created and fetched successfully.
        '500':
          description: Internal Server Error.

  # --- Organizations API Paths ---
  /organizations:
    post:
      summary: Create a new organization
      operationId: createOrganization
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name: { type: string }
              description: { type: string }
              nationality: { type: string }
              industry: { type: string }
              usedSoftware: { type: array, items: { type: string } }
            required:
              - name
      responses:
        '201':
          description: Organization created successfully
        '400':
          description: Invalid input

    get:
      summary: Get all organizations
      operationId: listOrganizations
      responses:
        '200':
          description: A list of organizations

  /organizations/{organizationId}:
    get:
      summary: Get a specific organization by ID
      operationId: getOrganizationById
      parameters:
        - name: organizationId
          in: path
          required: true
          type: string
          description: ID of the organization to retrieve
      responses:
        '200':
          description: Organization data
        '404':
          description: Organization not found

    put:
      summary: Update an existing organization
      operationId: updateOrganization
      parameters:
        - name: organizationId
          in: path
          required: true
          type: string
          description: ID of the organization to update
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name: { type: string }
              description: { type: string }
              status: { type: string }
              nationality: { type: string }
              industry: { type: string }
              usedSoftware: { type: array, items: { type: string } }
      responses:
        '200':
          description: Organization updated successfully
        '404':
          description: Organization not found
        '400':
          description: Invalid input

    delete:
      summary: Delete an organization
      operationId: deleteOrganization
      parameters:
        - name: organizationId
          in: path
          required: true
          type: string
          description: ID of the organization to delete
      responses:
        '204':
          description: Organization deleted successfully
        '404':
          description: Organization not found

  # --- Users API Paths ---
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              googleId: { type: string }
              email: { type: string }
              firstName: { type: string }
              lastName: { type: string }
              profilePictureUrl: { type: string }
              role: { type: string, enum: ['admin', 'editor', 'viewer'] }
              organizationId: { type: string }
            required:
              - googleId
              - email
              - firstName
              - lastName
              - role
              - organizationId
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

    get:
      summary: Get all users
      operationId: listUsers
      parameters:
        - name: organizationId
          in: query
          required: false
          type: string
          description: Optional filter by organization ID
      responses:
        '200':
          description: A list of users

  /users/{userId}:
    get:
      summary: Get a specific user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: ID of the user to retrieve
      responses:
        '200':
          description: User data
        '404':
          description: User not found

    put:
      summary: Update an existing user
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: ID of the user to update
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              firstName: { type: string }
              lastName: { type: string }
              profilePictureUrl: { type: string }
              role: { type: string, enum: ['admin', 'editor', 'viewer'] }
              organizationId: { type: string }
              status: { type: string, enum: ['active', 'inactive'] }
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found
        '400':
          description: Invalid input

    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /users/{userId}/last-login:
    put:
      summary: Update user's last login timestamp
      operationId: updateUserLastLogin
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: ID of the user to update last login for
      responses:
        '200':
          description: Last login updated successfully
        '404':
          description: User not found

  # --- Threat Actors API Paths ---
  /threat-actors:
    post:
      summary: Create a new threat actor
      operationId: createThreatActor
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name: { type: string }
              description: { type: string }
              aliases: { type: array, items: { type: string } }
              targetIndustries: { type: array, items: { type: string } }
              associatedCves: { type: array, items: { type: string } }
              countryOfOrigin: { type: string }
            required:
              - name
      responses:
        '201':
          description: Threat actor created successfully
        '400':
          description: Invalid input

    get:
      summary: Get all threat actors
      operationId: listThreatActors
      responses:
        '200':
          description: A list of threat actors

  /threat-actors/{threatActorId}:
    get:
      summary: Get a specific threat actor by ID
      operationId: getThreatActorById
      parameters:
        - name: threatActorId
          in: path
          required: true
          type: string
          description: ID of the threat actor to retrieve
      responses:
        '200':
          description: Threat actor data
        '404':
          description: Threat actor not found

    put:
      summary: Update an existing threat actor
      operationId: updateThreatActor
      parameters:
        - name: threatActorId
          in: path
          required: true
          type: string
          description: ID of the threat actor to update
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name: { type: string }
              description: { type: string }
              aliases: { type: array, items: { type: string } }
              targetIndustries: { type: array, items: { type: string } }
              associatedCves: { type: array, items: { type: string } }
              countryOfOrigin: { type: string }
      responses:
        '200':
          description: Threat actor updated successfully
        '404':
          description: Threat actor not found
        '400':
          description: Invalid input

    delete:
      summary: Delete a threat actor
      operationId: deleteThreatActor
      parameters:
        - name: threatActorId
          in: path
          required: true
          type: string
          description: ID of the threat actor to delete
      responses:
        '204':
          description: Threat actor deleted successfully
        '404':
          description: Threat actor not found

  # --- Incidents API Paths ---
  /incidents:
    post:
      summary: Create a new incident
      operationId: createIncident
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              title: { type: string }
              description: { type: string }
              status:
                {
                  type: string,
                  enum:
                    ['Open', 'Triaged', 'In Progress', 'Resolved', 'Closed'],
                }
              priority:
                { type: string, enum: ['Low', 'Medium', 'High', 'Critical'] }
              type: { type: string }
              cveIds: { type: array, items: { type: string } }
              threatActorIds: { type: array, items: { type: string } }
              reportedByUserId: { type: string }
              reportedByUserName: { type: string }
              assignedToUserId: { type: string }
              assignedToUserName: { type: string }
              organizationId: { type: string }
            required:
              - title
              - description
              - status
              - priority
              - reportedByUserId
              - reportedByUserName
              - organizationId
      responses:
        '201':
          description: Incident created successfully
        '400':
          description: Invalid input

    get:
      summary: Get all incidents
      operationId: listIncidents
      parameters:
        - name: organizationId
          in: query
          required: false
          type: string
          description: Optional filter by organization ID
      responses:
        '200':
          description: A list of incidents

  /incidents/{incidentId}:
    get:
      summary: Get a specific incident by ID
      operationId: getIncidentById
      parameters:
        - name: incidentId
          in: path
          required: true
          type: string
          description: ID of the incident to retrieve
      responses:
        '200':
          description: Incident data
        '404':
          description: Incident not found

    put:
      summary: Update an existing incident
      operationId: updateIncident
      parameters:
        - name: incidentId
          in: path
          required: true
          type: string
          description: ID of the incident to update
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              title: { type: string }
              description: { type: string }
              resolutionNotes: { type: string }
              status:
                {
                  type: string,
                  enum:
                    ['Open', 'Triaged', 'In Progress', 'Resolved', 'Closed'],
                }
              priority:
                { type: string, enum: ['Low', 'Medium', 'High', 'Critical'] }
              type: { type: string }
              cveIds: { type: array, items: { type: string } }
              threatActorIds: { type: array, items: { type: string } }
              assignedToUserId: { type: string }
              assignedToUserName: { type: string }
              dateResolved: { type: string, format: 'date-time' }
      responses:
        '200':
          description: Incident updated successfully
        '404':
          description: Incident not found
        '400':
          description: Invalid input

    delete:
      summary: Delete an incident
      operationId: deleteIncident
      parameters:
        - name: incidentId
          in: path
          required: true
          type: string
          description: ID of the incident to delete
      responses:
        '204':
          description: Incident deleted successfully
        '404':
          description: Incident not found

  # --- CVE API Paths ---
  /cves/latest:
    get:
      summary: Get a list of the latest CVEs
      operationId: getLatestCves
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          description: Number of latest CVEs to retrieve (default 10)
      responses:
        '200':
          description: A list of CVEs

  /cves/{cveId}:
    get:
      summary: Get a specific CVE by ID
      operationId: getCveById
      parameters:
        - name: cveId
          in: path
          required: true
          type: string
          description: ID of the CVE to retrieve (e.g., CVE-2023-1234)
      responses:
        '200':
          description: CVE data
        '404':
          description: CVE not found