import { useCallback } from 'react';
import jsPDF from 'jspdf';
import { type Incident } from '../../../api';

interface UsePDFExportProps {
  viewingIncident: Incident | null;
  aiSummary: string;
}

export const usePDFExport = ({ viewingIncident, aiSummary }: UsePDFExportProps) => {
  const exportToPDF = useCallback(() => {
    if (!viewingIncident || !aiSummary) return;

    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.text('AI Threat Intelligence Summary', 20, 20);
    
    // Add incident details
    doc.setFontSize(12);
    doc.text(`Incident: ${viewingIncident.title}`, 20, 35);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 45);
    doc.text(`Generated by: CTI Dashboard AI`, 20, 55);
    
    // Add summary content
    doc.setFontSize(10);
    const splitText = doc.splitTextToSize(aiSummary, 170);
    doc.text(splitText, 20, 75);
    
    // Save the PDF
    doc.save(`ai-summary-${viewingIncident.incidentId}-${new Date().toISOString().split('T')[0]}.pdf`);
  }, [viewingIncident, aiSummary]);

  return {
    exportToPDF
  };
}; 
